### ISSUE TITLE
Compile Issue

### ISSUE THREAD

**Issue by pierceboggan** [tom-mayer/Mono.Droid.Paypal#1]
Hi Tom,

I'm having some trouble getting this binding project to compile. Is there any way you could add .dll assemblies to the [Releases page](https://github.com/tom-mayer/Mono.Droid.Paypal/releases) of your repo?

Thanks,
Pierce Boggan

**Comment by tom-mayer** [comment]
Hi Pierce, 

I added a binary release for you. Just out of curiosity are you working on Windows or Mac. I just checked out a clean version of the repository and it did build. What was the error?

Cheers
Tom
